from tkinter import *
global text1
def onclick(num):
    pass
def clear():
    pass
def equal():
    pass
window=Tk()
window.configure(background="#F1948A")
textbox1=Entry(window,width=50,bg="white")
textbox1.grid(columnspan=4,ipadx=50)
b1=Button(window,text="1",width=10,command=onclick(1))
b1.grid(row=1,column=0)
b2=Button(window,text="2",width=10,command=onclick(2))
b2.grid(row=1,column=1)
b3=Button(window,text="3",width=10,command=onclick(3))
b3.grid(row=1,column=2)
b4=Button(window,text="+",width=10,command=onclick)
b4.grid(row=1,column=3)
b5=Button(window,text="4",width=10,command=onclick(4))
b5.grid(row=2,column=0)
b6=Button(window,text="5",width=10,command=onclick(5))
b6.grid(row=2,column=1)
b7=Button(window,text="6",width=10,command=onclick(6))
b7.grid(row=2,column=2)
b8=Button(window,text="-",width=10,command=onclick)
b8.grid(row=2,column=3)
b9=Button(window,text="7",width=10,command=onclick(7))
b9.grid(row=3,column=0)
b10=Button(window,text="8",width=10,command=onclick(8))
b10.grid(row=3,column=1)
b11=Button(window,text="9",width=10,command=onclick(9))
b11.grid(row=3,column=2)
b12=Button(window,text="*",width=10,command=onclick)
b12.grid(row=3,column=3)
b13=Button(window,text="=",width=10,command=equal)
b13.grid(row=4,column=0)
b14=Button(window,text="0",width=10,command=onclick(0))
b14.grid(row=4,column=1)
b15=Button(window,text="clr",width=10,command=clear)
b15.grid(row=4,column=2)
b16=Button(window,text="/",width=10,command=onclick)
b16.grid(row=4,column=3)
window.mainloop()
